version: 2
jobs:
  build:
    docker:
      - image: 'circleci/node:12.9.1-browsers'
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: npm ci
      - save_cache:
          paths:
            - node_modules
            - sandbox/node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      # run tests!
      - run: chmod -R 777 /usr/local/lib/node_modules/@briebug
      - run: npm test
